### ISSUE TITLE
SWMM broken plugin for QGis 2.8.6-wien

### ISSUE THREAD

**Issue by FlorenciaSrur** [Oslandia/qgis-swmm#15]
I installed the SWMM plugin following the readme instructions but the pluggin seems to be broken as see in the image I attached here.
Could you help me?
I am using Ubuntu 16.04, Qgis version 2.8.6-wien and SWMM 5.0.011
Thank You
Florencia Srur
 ![Uploading Qgis_swmm.png…]()

**Comment by sjib** [comment]
Is this plugin still maintained?

**Comment by vmora** [comment]
@sjib I've not worked a lot on the plugin those past years, but some PR have been made and integrated, so I guess some people use it.

@FlorenciaSrur I can't see the image you posted to illustrate the problem.

**Comment by sjib** [comment]
I also get an error when loading the plugin with QGIS 2.8.13

Couldn't load plugin 'qgis-swmm' 

ImportError: No module named parameters 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS 2.18.13/apps/qgis/./python\qgis\utils.py", line 308, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS 2.18.13/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/stefan/.qgis2/python/plugins\qgis-swmm\__init__.py", line 3, in 
    from SwmmAlgorithmProvider import SwmmAlgorithmProvider
  File "C:/PROGRA~1/QGIS 2.18.13/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/stefan/.qgis2/python/plugins\qgis-swmm\SwmmAlgorithmProvider.py", line 33, in 
    from SwmmAlgorithm import SwmmAlgorithm
  File "C:/PROGRA~1/QGIS 2.18.13/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/stefan/.qgis2/python/plugins\qgis-swmm\SwmmAlgorithm.py", line 41, in 
    from processing.parameters import ParameterVector
  File "C:/PROGRA~1/QGIS 2.18.13/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named parameters


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.13 Las Palmas, 8cba0bb9eb 

Python Path:
C:/PROGRA~1/QGIS 2.18.13/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS 2.18.13/apps/qgis/./python
C:/Users/stefan/.qgis2/python
C:/Users/stefan/.qgis2/python/plugins
C:/PROGRA~1/QGIS 2.18.13/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS 2.18.13\bin\python27.zip
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\DLLs
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\lib
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS 2.18.13\bin
C:\PROGRA~1\QGIS 2.18.13\apps\Python27
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS 2.18.13\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/stefan/.qgis2//python
C:/Users/stefan/.qgis2/python/plugins\qgis_resource_sharing
C:\Users\stefan\.qgis2\python\plugins\qgis_resource_sharing
C:\Users\stefan\.qgis2\python\plugins\qgis_resource_sharing\ext_libs
C:\Users\stefan\.qgis2\python\plugins\DigitizingTools\tools

Any hint what could be wrong?

**Comment by sjib** [comment]
Should be solved with https://github.com/Oslandia/qgis-swmm/pull/19
